app/src/main/java/find/ui/scan/ScanFragment.kt
app/src/main/res/drawable/border_bottom_gray_bd_fill.xml
app/src/main/res/layout/fragment_scan.xml
app/src/main/res/values/colors.xml

- Setting ViewPager Adapter
- Setting TabLayoutMediator
- Modify fragment_scan.xml
- Add drawable and color for Underline Tab

[feature] ViewPager and TabLayout In ScanFragment #14

---

app/src/main/res/drawable/border_gray_fill_round_25.xml
app/src/main/res/drawable/border_mint_fill_circle.xml
app/src/main/res/drawable/border_purple_fill_round_40.xml
app/src/main/res/layout/fragment_find.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

- Layout FindFragment
- Add color gray_e0 and mint_81ec_0.15
- Create Drawables for Background

[layout] FindFragment #16

---

app/src/main/java/find/ui/find/FindBinding.kt
app/src/main/java/find/ui/find/FindFragment.kt
app/src/main/java/find/ui/find/FindViewModel.kt
app/src/main/res/drawable/border_mint_fill_round_25.xml
app/src/main/res/drawable/border_mint_stroke_fill_circle.xml
app/src/main/res/layout/fragment_find.xml

- Create FindViewModel
- Create FindBinding
- Create Drawables for Button Selector
- Apply Buttons Selector
- DataBinding for FindFragment

[feature] binding.btnFindOpponent Active #21

---

app/src/main/AndroidManifest.xml
app/src/main/java/find/ui/ui/find/FindBinding.kt
app/src/main/java/find/ui/ui/find/FindFragment.kt
app/src/main/java/find/ui/ui/find/FindViewModel.kt
app/src/main/java/find/ui/ui/found/FoundFragment.kt
app/src/main/java/find/ui/ui/main/MainActivity.kt
app/src/main/java/find/ui/ui/matching/MatchingFragment.kt
app/src/main/java/find/ui/ui/mypage/MyPageFragment.kt
app/src/main/java/find/ui/ui/profile/CreateProfileActivity.kt
app/src/main/java/find/ui/ui/reserve/ReserveFragment.kt
app/src/main/java/find/ui/ui/scan/ScanFragment.kt
app/src/main/java/find/ui/util/NestedScrollableHost.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_find.xml
app/src/main/res/layout/fragment_found.xml
app/src/main/res/layout/fragment_matching.xml
app/src/main/res/layout/fragment_my_page.xml
app/src/main/res/layout/fragment_reserve.xml
app/src/main/res/layout/fragment_scan.xml

- Update Package
- Create ui Package
- Create NestedScrollableHost

[feature] Create NestedScrollableHost #25

---

app/src/main/res/drawable/border_white_fill_round_10.xml
app/src/main/res/layout/dialog_create_profile.xml
app/src/main/res/values/strings.xml

- Create Layout for Profile Dialog
- Add drawble for background
- Modify strings.xml

[layout] Create Profile Dialog #29

---

app/src/main/java/find/ui/ui/mypage/MyPageFragment.kt
app/src/main/java/find/ui/ui/profile/CreateProfileDialog.kt
app/src/main/res/layout/dialog_create_profile.xml

- Modify Dialog size
- Set Dialog in MyPage
- Connect MyPage and Profile with Dialog

[feature] Set Dialog in MyPageFragment #32

---

app/build.gradle
app/src/main/java/find/ui/ui/find/FindFragment.kt
app/src/main/java/find/ui/ui/mypage/MyPageFragment.kt
app/src/main/java/find/ui/ui/scan/ScanFragment.kt
app/src/main/java/find/ui/util/AutoClearedValue.kt
app/src/main/java/find/ui/util/NestedScrollableHost.kt
build.gradle

- Create AutoClearedValue
- Apply AutoClearedValue

[feature] Apply AutoClearedValue #36

---

app/src/main/java/find/ui/ui/main/MainActivity.kt
app/src/main/java/find/ui/ui/scan/ScanFragment.kt
app/src/main/java/find/ui/ui/values/ValuesActivity.kt
app/src/main/res/layout/activity_values.xml

- Setting TabLayoutMediator In ValuesActivity
- Setting ViewPager Adapter In ValuesActivity

[feature] ViewPager and TabLayout In ValuesActivity #40

---

app/src/main/res/drawable/border_gray_line_round_25.xml
app/src/main/res/drawable/border_purple_line_round_25.xml
app/src/main/res/drawable/border_white_fill_round_14.xml
app/src/main/res/layout/activity_values.xml
app/src/main/res/layout/fragment_question.xml
app/src/main/res/layout/item_question.xml

- Create item_question.xml
- Layout item_question.xml
- Add Background ViewPager in ValuesActivity
- Modify fragment_question.xml

[layout] Question Item #42

---

app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/values/styles.xml

- Create styles.xml
- Remove Duplicate code using styles.xml

[refactor] Remove Duplicate code #49

---

app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

- Create Basic Information View
- Modify styles.xml for improved code

[layout] Basic Information in Create Profile #51

---

app/src/main/res/layout/dialog_profile_info.xml
app/src/main/res/values/strings.xml

- Create Layout Profile Info Dialog

[layout] Dialog for Text Input  #53

---

app/src/main/java/find/ui/ui/profile/CreateProfileActivity.kt
app/src/main/java/find/ui/ui/profile/InfoDialogFragment.kt
app/src/main/java/find/ui/util/DialogResize.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/dialog_profile_info.xml

- Create Info DialogFragment
- Create DialogResize 
- Show Dialog Input to Activity
- Change Dialog data on ClickEvent using bundle

[feature] Show Dialog for Text Input #56

---

app/src/main/AndroidManifest.xml
app/src/main/java/find/ui/ui/profile/IntroductionActivity.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/activity_introduction.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

- Layout Introduction
- Modify styles.xml on duplicate

[layout] Layout Introduction #58

---

app/src/main/java/find/ui/ui/profile/CreateProfileActivity.kt
app/src/main/java/find/ui/ui/profile/IntroductionActivity.kt
app/src/main/java/find/ui/ui/profile/ProfileBinding.kt
app/src/main/java/find/ui/ui/profile/ProfileViewModel.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/activity_introduction.xml

- Create ProfileBinding
- Create ProfileViewModel
- Change Color by length
- Set TextWatcher for Changing length label
- Connect with Create Profile Activity

[feature] Binding In Introduction #64

---

app/src/main/AndroidManifest.xml
app/src/main/java/find/ui/ui/dialog/CreateProfileDialog.kt
app/src/main/java/find/ui/ui/dialog/InfoDialogFragment.kt
app/src/main/java/find/ui/ui/mypage/IntroductionActivity.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/java/find/ui/ui/mypage/MyPageBinding.kt
app/src/main/java/find/ui/ui/mypage/MyPageFragment.kt
app/src/main/java/find/ui/ui/profile/ProfileActivity.kt
app/src/main/java/find/ui/ui/profile/ProfileViewModel.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/activity_introduction.xml
app/src/main/res/layout/activity_profile.xml
app/src/main/res/layout/dialog_create_profile.xml
app/src/main/res/layout/dialog_profile_info.xml

- Create Dialog Package
- Create Interview Package
- Rearrange about Profile Package

[refactor] Rearrange the Package #70

---

app/src/main/AndroidManifest.xml
app/src/main/java/find/ui/ui/interview/InterviewActivity.kt
app/src/main/java/find/ui/ui/mypage/MyPageFragment.kt
app/src/main/res/layout/activity_interview.xml
app/src/main/res/values/strings.xml

- Layout InterviewActivity
- Connect InterviewActivity to MyPage

[layout] InterviewActivity #72

---

app/src/main/java/find/ui/ui/interview/AskFragment.kt
app/src/main/java/find/ui/ui/interview/InterviewActivity.kt
app/src/main/res/layout/activity_interview.xml
app/src/main/res/layout/fragment_ask.xml

- Setting ViewPager and TabLayout In InterviewActivity
- Create AskFragment

[feature] ViewPager and TabLayout In InterviewActivity #74

---

app/src/main/res/layout/activity_interview.xml
app/src/main/res/layout/fragment_ask.xml
app/src/main/res/layout/item_ask.xml
app/src/main/res/layout/item_photo.xml
app/src/main/res/values/strings.xml

- Create ask items
- Create photo items
- Complete Interview Layout

[layout] Interview Details #78

---

app/src/main/java/find/ui/ui/dialog/BasicDialog.kt
app/src/main/res/layout/dialog_basic.xml
app/src/main/res/values/strings.xml

- Create BasicDialog
- Layout BasicDialog

[feature] Dialog Unification #54

---

app/src/main/java/find/ui/ui/interview/AskFragment.kt
app/src/main/java/find/ui/ui/interview/InterviewAdapter.kt
app/src/main/java/find/ui/ui/interview/InterviewBinding.kt
app/src/main/java/find/ui/ui/interview/InterviewViewModel.kt
app/src/main/java/find/ui/ui/mypage/MyPageBinding.kt
app/src/main/java/find/ui/ui/profile/ProfileViewModel.kt
app/src/main/res/layout/activity_introduction.xml
app/src/main/res/layout/fragment_ask.xml
app/src/main/res/layout/item_ask.xml

- Binding EditText In InterviewActivity and RecyclerView
- Change color by length
- Change label by length

[feature] Binding EditText In InterviewActivity #80

---

app/src/main/res/drawable/border_white_fill_round_4.xml
app/src/main/res/layout/activity_answer.xml
app/src/main/res/layout/item_answer_filter.xml
app/src/main/res/values/colors.xml

- Layout ItemAnswerFilter
- Create Drawable for radius 4
- Add #269980fa In Color
- Add ScrollView in AnswerActivity

[layout] ItemAnswerFilter #87

---

app/src/main/java/find/ui/ui/mypage/IntroductionActivity.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/res/layout/activity_create_profile.xml

- Change Introduction Button -> TextView
- Create Introduction View with content
- Using resigerForActivityResult

[feature] Show Introduction In CreateProfile #83

---

app/src/main/java/find/ui/ui/dialog/PickerDialog.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/dialog_picker.xml
app/src/main/res/values/colors.xml

- Create Picker Dialog
- Connect Dialog with Create Profile

[layout] PickerDialog #91

---

app/src/main/res/layout/activity_values.xml
app/src/main/res/layout/fragment_question.xml

- Delete RecyclerView
- Add ViewPager2

[layout] Change RecyclerView to ViewPager2 In QuestionFragment #94

---

app/src/main/java/find/ui/ui/question/Question.kt
app/src/main/java/find/ui/ui/question/QuestionAdapter.kt
app/src/main/java/find/ui/ui/question/QuestionFragment.kt

- Create QuestionAdapter
- Create Data Class Question
- Setting binding.vpQuestion.adapter

[feature] Setting QuestionAdapter #96

---

app/src/main/java/find/ui/ui/question/QuestionAdapter.kt
app/src/main/java/find/ui/ui/question/QuestionBinding.kt
app/src/main/res/layout/item_question.xml
app/src/main/res/values/strings.xml

- Binding Question
- Binding adapterPosition
- Create QuestionBinding

[feature] Binding for item_question #98

---

app/src/main/java/find/ui/ui/dialog/InfoDialog.kt
app/src/main/java/find/ui/ui/dialog/PickerDialog.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/java/find/ui/ui/profile/ProfileViewModel.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/dialog_picker.xml
app/src/main/res/layout/dialog_profile_info.xml
app/src/main/res/values/styles.xml

- Show Content from PickerDialog to CreateProfile
- Connect PickerDialog with CreateProfile
- Setting Data for Picker
- Change Type Ok button -> textView

[feature] Show Content from PickerDialog #93

---

app/src/main/res/color/selector_question_chip.xml
app/src/main/res/layout/item_question.xml

- Create Chip Group and Chip
- Create Color Resource

[feature] Chip In item_question.xml #108

---

app/src/main/res/layout/fragment_find.xml
app/src/main/res/layout/item_find_my_value.xml

- Create RecyclerView
- Create item_find_my_value

[layout] Add RecyclerView FindFragment #110

---

app/src/main/java/find/ui/ui/find/FindFragment.kt
app/src/main/java/find/ui/ui/find/FindMyValueAdapter.kt
app/src/main/java/find/ui/ui/find/FindViewModel.kt
app/src/main/res/layout/fragment_find.xml

- Create FindMyValueAdapter
- Create tempList in FindViewModel
- Setting Visibility
- Setting ScrollView

[feature] FindMyValueAdapter #112

---

app/src/main/java/find/ui/ui/find/FindBinding.kt
app/src/main/java/find/ui/ui/find/FindViewModel.kt
app/src/main/res/layout/fragment_find.xml

- Create Boolean Value in FindViewModel
- Setting Boolean Value

[feature] Change Find Button Active Logic #114

---

app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/item_photo.xml

- Layout item_photo
- Set RecyclerView in Create Profile

[layout] Change Profile Picture to RecyclerView #106

---

app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/java/find/ui/ui/picture/PictureAdapter.kt
app/src/main/java/find/ui/ui/picture/PictureViewModel.kt
app/src/main/java/find/ui/ui/picture/ProfilePicture.kt
app/src/main/res/layout/item_photo.xml

- Create PictureAdapter
- Create PictureViewModel
- Set Default Image in ViewModel
- Create picture package

[feature] PictureAdapter #119

---

app/src/main/java/find/ui/ui/dialog/TwoButtonDialog.kt
app/src/main/res/drawable/border_gray_line_round_10.xml
app/src/main/res/layout/dialog_two_button.xml
app/src/main/res/values/strings.xml

- Create TwoButtonDialog
- Layout TwoButtonDialog
- Modify OneButtonDialog TAG

[feature] Create TwoButtonDialog #120

---

app/src/main/java/find/ui/ui/dialog/PictureDialog.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/res/layout/dialog_picture.xml
app/src/main/res/values/strings.xml

- Create Picture Dialog
- Connect Dialog with Create Profile

[layout] PictureDialog #123

---

app/src/main/java/find/ui/ui/dialog/OneButtonDialog.kt
app/src/main/java/find/ui/ui/dialog/TwoButtonDialog.kt
app/src/main/java/find/ui/ui/found/FoundFragment.kt
app/src/main/java/find/ui/ui/mypage/MyPageFragment.kt

[refactor] OneButtonDialog and TwoButtonDialog #128

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/find/ui/ui/dialog/PictureDialog.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/java/find/ui/ui/picture/PictureAdapter.kt
app/src/main/java/find/ui/ui/picture/PictureBinding.kt
app/src/main/java/find/ui/ui/picture/PictureViewModel.kt
app/src/main/res/layout/item_photo.xml

- Add gradle for Glide
- Add permission to Manifest
- Upload Picture

[feature] Upload Picture #122

---

app/src/main/java/find/ui/ui/dialog/AddPictureDialog.kt
app/src/main/java/find/ui/ui/interview/InterviewActivity.kt
app/src/main/java/find/ui/ui/interview/InterviewViewModel.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/java/find/ui/ui/picture/PictureAdapter.kt
app/src/main/java/find/ui/ui/picture/PictureViewModel.kt
app/src/main/res/layout/activity_create_profile.xml
app/src/main/res/layout/activity_interview.xml
app/src/main/res/layout/dialog_add_picture.xml

- Set Main Mark In Profile Picture
- Separate PictureList Interterview and Profile
- Rename PictureDialog -> AddPictureDialog

[feature] Set Main Mark In Profile Picture #137

---

app/src/main/java/find/ui/ui/dibs/DibsFragment.kt
app/src/main/java/find/ui/ui/feeling/FeelingFragment.kt
app/src/main/java/find/ui/ui/matching/MatchingFragment.kt
app/src/main/res/layout/fragment_dibs.xml
app/src/main/res/layout/fragment_feeling.xml
app/src/main/res/layout/fragment_matching.xml
app/src/main/res/values/strings.xml

- Layout MatchingFragment
- Create FeelingFragment
- Create DibsFragment

[layout] MatchingFragment #141

---

app/src/main/res/layout/fragment_dibs.xml
app/src/main/res/layout/fragment_feeling.xml
app/src/main/res/values/strings.xml

- Layout FeelingFragment for empty
- Modify Layout DibsFragment

[layout] FeelingFragment #146

---

app/src/main/java/find/ui/ui/dialog/ModifyPictureDialog.kt
app/src/main/java/find/ui/ui/interview/InterviewActivity.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/java/find/ui/ui/picture/PictureViewModel.kt
app/src/main/java/find/ui/ui/picture/ProfilePicture.kt

- Main Button disabled for Main Picture
- Show Main mark for Main Picture

[feature] Show Main mark and disabled #142

---

app/src/main/res/drawable/border_white_fill_round_30.xml
app/src/main/res/layout/item_feeling_send_get.xml

- Layout item_feeling_send_get.xml
- Create Drawable for Button Background

[layout] item_feeling_send_get.xml #154

---

app/src/main/java/find/ui/ui/dialog/AddPictureDialog.kt
app/src/main/java/find/ui/ui/dialog/ModifyPictureDialog.kt
app/src/main/java/find/ui/ui/interview/InterviewActivity.kt
app/src/main/java/find/ui/ui/interview/InterviewViewModel.kt
app/src/main/java/find/ui/ui/mypage/MyPageActivity.kt
app/src/main/res/values/strings.xml

- Click Picture as Cursor
- Separate Dialog in Interview and Profile
- INVISIBLE tv_picture_main in Interview

[feature] Click Picture as Cursor #157

---

app/src/main/java/find/ui/ui/matching/DibsAdapter.kt
app/src/main/java/find/ui/ui/matching/FeelingAdapter.kt
app/src/main/java/find/ui/ui/matching/FeelingConnectedAdapter.kt

- Create DibsAdapter
- Create FeelingAdapter
- Create FeelingConnectedAdapter

[feature] Adapter for RecyclerView in MatchingFragment #161

---

app/src/main/java/find/ui/ui/matching/DibsAdapter.kt
app/src/main/java/find/ui/ui/matching/FeelingAdapter.kt
app/src/main/java/find/ui/ui/matching/FeelingConnectedAdapter.kt
app/src/main/java/find/ui/ui/matching/MatchingDiffUtil.kt
app/src/main/java/find/ui/ui/matching/MatchingViewHolder.kt

- Create MatchingDiffUtil
- Create MatchingViewHolder
- Refactoring DibsAdapter
- Refactoring FeelingAdapter
- Refactoring FeelingConnectedAdapter

[refactor] Create MatchingDiffUtil and MatchingViewHolder #164

---

app/src/main/java/find/ui/ui/dibs/DibsAdapter.kt
app/src/main/java/find/ui/ui/feeling/FeelingAdapter.kt
app/src/main/java/find/ui/ui/feeling/FeelingConnectedAdapter.kt

- Package Moving DibsAdapter
- Package Moving FeelingAdapter
- Package Moving FeelingConnectedAdapter

[refactor] Package Moving Dibs and Feeling #166

---

app/src/main/java/find/ui/ui/find/FindBinding.kt
app/src/main/java/find/ui/ui/found/ResponseFound.kt
app/src/main/res/layout/item_found.xml
app/src/main/res/values/strings.xml

- Convert to Binding Layout item_found.xml

[feature] DataBinding for RecyclerView item in FoundFragment #171
